#------------------
# GitHub Action
#------------------

name: My-GitHubActions-Basics
env:
  APPLICATION_NAME    : "MyFlask"
  DEPLOY-PACKAGE-NAME : "flask-deploy-ver-${{ github.sha }}"

on:
  push:
    branches: 
      - main

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello Message Testing
      run: echo "Hello World from Testing job"

    - name: Execute a few commands
      run: |
        echo "Print Hello message 1"
        echo "Print Hello message 2"
        echo "Application name: ${{ env.APPLICATION_NAME }}"

  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]

    steps:
    - name: Print Hello Message Deploy
      run: echo "Hello World from Deploy job"

    - name: Printing a Deployment package
      run: echo "Deploy package name is ${{ env.DEPLOY-PACKAGE-NAME }}"
      
