#------------------
# GitHub Action
#------------------

name: My-GitHubActions-Basics
env:
  APPLICATION_NAME    : "MyFlask"
  DEPLOY-PACKAGE-NAME : "flask-deploy-ver-${{ github.sha }}"

on:
  push:
    branches: 
      - main

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello Message Testing
      run : echo "Hello World from Testing job"

    - name: Execute a few commands
      run : |
        echo "Print Hello message 1"
        echo "Print Hello message 2"
        echo "Application name: ${{ env.APPLICATION_NAME }}"

    - name: List current folder
      run : ls -la

    - name: Git clone my repo
      uses: actions/checkout@v1

    - name: List current folder
      run : ls -la

  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    env:
      VAR1 : "Deploy variable 1"
      VAR2 : "Deploy variable 2"

    steps:
    - name: Print Hello Message Deploy
      run : echo "Hello World from Deploy job"

    - name: Printing a Deployment package
      run : echo "Deploy package name is ${{ env.DEPLOY-PACKAGE-NAME }}"

    - name: Test some packages if they are there 1
      run : aws --version

    - name: Test some packages if they are there 2
      run : zip

    - name: Print varables
      run : |
        echo "Var1 = ${{ env.VAR1 }}"
        echo "Var2 = ${{ env.VAR2 }}"
        echo "Var3 = $LOCAL_VAR"
      env :
        LOCAL_VAR : "Step local variable"
      
